name: Docker CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build --target production -t ${{ secrets.DOCKER_USERNAME }}/devboard-backend:latest -t ${{ secrets.DOCKER_USERNAME }}/devboard-backend:${{ github.sha }} ./backend

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devboard-frontend:latest -t ${{ secrets.DOCKER_USERNAME }}/devboard-frontend:${{ github.sha }} ./frontend

      - name: Build Nginx Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devboard-nginx:latest -t ${{ secrets.DOCKER_USERNAME }}/devboard-nginx:${{ github.sha }} ./nginx

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-backend:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-frontend:${{ github.sha }}

      - name: Push Nginx Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devboard-nginx:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd C:/server/devboard-docker
            docker pull ${{ secrets.DOCKER_USERNAME }}/devboard-backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/devboard-frontend
            docker compose down
            docker compose up -d